# Boorupaper Configuration - Generated Fri Jul 31 02:03:05 AM +06 2026

# --- Server ---
# Uncomment the server you want to use and comment out the others.
#
#SERVER_TYPE="moebooru"
#BASE_URL="https://konachan.net"

# SERVER_TYPE="danbooru"
# BASE_URL="https://danbooru.donmai.us"
# DANBOORU_LOGIN=""
# DANBOORU_API_KEY=""

SERVER_TYPE="wallhaven"
BASE_URL="https://wallhaven.cc"
WALLHAVEN_API_KEY="9TKHCOKv9D2JlMwny6l5OwgEBcJjg8m8"

#SERVER_TYPE="safebooru"
#BASE_URL="https://safebooru.org"

# --- Display Server ---
DISPLAY_SERVER="wayland"

# --- Wallpaper Command ---
WALLPAPER_COMMAND="awww img {IMAGE} --transition-type any --transition-fps 60 --transition-duration 1"

# --- Basic Search Parameters ---
LIMIT=200
RATING="s"
ORDER="random"
PAGE=random

# --- Advanced Filters ---
MAX_FILE_SIZE="0"
MIN_FILE_SIZE="1MB"
# --- Resolution ---
ASPECT_RATIO="16:10,16:9"

# --- Content ---
PREFERRED_FORMAT="jpg"
ANIMATED_ONLY=false

# --- Random Tags ---
RANDOM_TAGS_COUNT=1
RANDOM_TAGS_LIST="/home/tawsif/.config/boorupaper/discovered_tags_wallhaven.txt"
DISCOVER_LIMIT=200

# --- Cache & Performance ---
PRELOAD_COUNT=3
MAX_PRELOAD_CACHE=20

# --- Favorites ---
FAVORITES_DIR="/home/tawsif/Pictures/Wallpapers"

# --- Notifications ---
ENABLE_NOTIFICATIONS=true
NOTIFY_TIMEOUT=1000
NOTIFY_PRELOAD=false

# --- Logging ---
ENABLE_LOGGING=true
LOG_FILE="/home/tawsif/.config/boorupaper/boorupaper.log"
LOG_LEVEL="detailed"
LOG_ROTATION=true
