general {
    lock_cmd = pidof hyprlock || hyprlock       # dbus/loginctl lock command
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # turn on display after sleep
}

# 1. Dim screen (Optional: keep this active or add the AC check)
listener {
    timeout = 150
    on-timeout =  [ "$(cat /sys/class/power_supply/ADP1/online)" = 0 ] && brightnessctl -s set 1
    on-resume = brightnessctl -r
}

# 2. Lock Screen (ONLY if on battery)
listener {
    timeout = 300
    # Logic: If ADP1 is 0 (battery), then try to lock.
    on-timeout = [ "$(cat /sys/class/power_supply/ADP1/online)" = 0 ] && loginctl lock-session
}

# 3. DPMS Off (Screen power off - ONLY if on battery)
listener {
    timeout = 330
    # Logic: Only turn off screen if on battery and already locked
    on-timeout = [ "$(cat /sys/class/power_supply/ADP1/online)" = 0 ] && hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 4. Suspend (ONLY if on battery)
listener {
    timeout = 1800
    # Logic: Only suspend if AC is 0
    on-timeout = [ "$(cat /sys/class/power_supply/ADP1/online)" = 0 ] && systemctl suspend
}
