#
# Autostart Configuration
#
# This file contains applications and scripts that will be executed once when Hyprland starts.
#
# For more information, see the Hyprland wiki:
# https://wiki.hyprland.org/Configuring/Autostart/
#

exec-once = wayle panel start
exec-once = mako
exec-once = hyprctl setcursor Bibata-Modern-Classic 22
exec-once = hypridle
exec-once = awww-daemon
exec-once = awww img ~/.cache/boorupaper/current.jpg --transition-fps 60 --transition-duration 1
exec-once = awww img ~/.cache/boorupaper/current.png --transition-fps 60 --transition-duration 1
exec-once = wl-paste --type text --watch cliphist store
exec-once = nm-applet
exec-once = blueman-applet
exec-once = systemctl --user start hyprpolkitagent
