#
# Cursor Configuration
#
# This file contains cursor settings for Hyprland.
#
# For more information, see the Hyprland wiki:
# https://wiki.hyprland.org/Configuring/Variables/

cursor {
    invisible = false
    inactive_timeout = 5
    hide_on_key_press = true
}
