[general]
import = ["~/.config/alacritty/themes/tokyo-night.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding = { x = 8, y = 8 }
dynamic_padding = true
decorations = "full"
startup_mode = "Maximized"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 14.0
builtin_box_drawing = true

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.offset]
x = 0
y = 1

[font.glyph_offset]
x = 0
y = 0

[colors.primary]
background = "#1e1f2e" # Slightly lighter background
foreground = "#c0caf5"

[colors.normal]
black = "#1a1b26"   # Darker black for better contrast
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"   # Brighter white

[colors.bright]
black = "#414868"
red = "#ff7a93"     # Brighter red
green = "#b9f27c"   # Brighter green
yellow = "#ff9e64"  # Brighter yellow
blue = "#7da6ff"    # Brighter blue
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#d5daf5"   # Much brighter white

[[colors.indexed_colors]]
index = 16
color = "#ff9e64"

[[colors.indexed_colors]]
index = 17
color = "#db4b4b"

[cursor]
blink_interval = 750
unfocused_hollow = true
thickness = 0.15

[cursor.style]
shape = "Block"
blinking = "On"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[bell]
animation = "EaseOutExpo"
duration = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
command = "xdg-open"
post_processing = true
mouse = { enabled = true, mods = "None" }
binding = { key = "U", mods = "Control|Shift" }

[[keyboard.bindings]]
key = "Back"
mods = "Control"
chars = "\u0017"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "PasteSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "F11"
mods = "None"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "PageUp"
mods = "None"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "None"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
action = "ScrollToBottom"

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
print_events = false
